### ISSUE TITLE
[FEATURE] Add a method to play a sound from a string

### ISSUE THREAD

**Issue by Aeltumn** [Ayfri/Kore#82]
### What module does this feature apply to?

DSL

### Feature description

Currently you can only play a sound using the generated definitions (as far as I could find), but you can add your own sounds using resource packs, so it would be nice to have a version that lets you freely pick the sound id to play.

### My issue is not duplicated

- [X] This is not a duplicate

**Comment by Ayfri** [comment]
That's a mistake I made, instead of using `SoundArgument` I've used `Sounds`, a fix will release for 1.20.5-pre1 !

Then you'll be able to write `SoundArgument("my_sound_name", "my_namespace")` and put that as a parameter.
Then also add a method for playing a sound using only a string if you want, but it's preferred to use `Argument` instances as you can keep the namespace and the name separated, it's easier to change later.

**Comment by Aeltumn** [comment]
SoundArgument does make more sense, that'd solve it.
